title: Close to the Metal
author: Sandhya Chandramohan
email: s4ndhyac@gmail.com
url: https://blog.sandhya.dev
description: > # this means to ignore newlines until "show_excerpts:"
  Distributed Systems, Hardware hacking and growth
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://secure.gravatar.com/avatar/898896292c00189f5ec1a689409de2e2?s=192" # avatar in about page
  about_you: a short description about you. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: s4ndhya
    github:  s4ndhyac
    rss: RSS
    # dribbble: 
    facebook: sandhya.chandramohan
    # flickr:   
    instagram: sandhya.chandramohan 
    linkedin: sandhyachandramohan
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
remote_theme: s4ndhyac/moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
